# Web Server Port
port: 7355

# Chrome settings
chrome:
  # Path to Chrome binaries on Linux (useChromium must be false)
  bin: "/usr/bin/google-chrome"

  # Path to Chrome binaries on Windows (useChromium must be false)
  binWindows: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"

  # If useChromium is true, then the locally install chromium from puppeteer will be used
  # If useChromium is false, then the bin or binWindows will be used
  useChromium: true

  # Uses Chrome in incognito mode for each request. This prevents cookies from being cached
  useIncognito: true

  # The number of simultanious requests that can handled at once
  concurrentPages: 8

  # Will open chrome windows. Usefull for debuggin but will not allow PDFs to be generated
  headless: true

  # Disables the security sandbox
  noSandbox: false

  # Disables GPU
  disableGpu: true

# Comma separated list of presets that will be used by default if none is given in the request
presetDefault: null

# Comma separated list of presets that every request will use. The presetDefault or preset provided in the request will override settings in the base preset.
presetBase: "base"

# Comma separated list of presets that every request will use. Settings in the final preset will override the preset given in the request.
presetFinal: null

# Presets may be used
presets:
  base:
    margins: ".5in"
  extractHeaders:
    header:
      selector: "hpp-print-header"
    footer:
      selector: "hpp-print-footer"
