# Web Server Port
port: 7355

# Chrome settings
chrome:
  # Path to Chrome binaries on Linux (useChromium must be false)
  bin: "/usr/bin/google-chrome"

  # Path to Chrome binaries on Windows (useChromium must be false)
  binWindows: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"

  # If useChromium is true, then the locally install chromium from puppeteer will be used
  # If useChromium is false, then the bin or binWindows will be used
  useChromium: true

  # Uses Chrome in incognito mode for each request. This prevents cookies from being cached
  useIncognito: true

  # The number of simultanious requests that can handled at once
  concurrentPages: 8

  # Will open chrome windows. Usefull for debuggin but will not allow PDFs to be generated
  headless: true

  # Disables the security sandbox
  noSandbox: false

  # Disables GPU
  disableGpu: true

# Comma separated list of presets that will be used by default if none is given in the request
presetDefault: null

# Comma separated list of presets that every request will use. The presetDefault or preset provided in the request will override settings in the base preset.
presetBase: "base"

# Comma separated list of presets that every request will use. Settings in the final preset will override the preset given in the request.
presetFinal: null

# Presets may be used
presets:
  base:
    margins: ".5in"
    header:
      selector: ".hpp-print-header"
      scalingFudge: 0.75
    footer:
      selector: ".hpp-print-footer"
      scalingFudge: 0.75

formats:
  Letter: ["8.5in", "11in"]
  Legal: ["8.5in", "14in"]
  Tabloid: ["11in", "17in"]
  Ledger: ["17in", "11in"]
  A0: ["33.1in", "46.8in"]
  A1: ["23.4in", "33.1in"]
  A2: ["16.54in", "23.4in"]
  A3: ["11.7in", "16.54in"]
  A4: ["8.27in", "11.7in"]
  A5: ["5.83in", "8.27in"]
  A6: ["4.13in", "5.83in"]

headerFooterCssResetHtml: |-
  <style type="text/css">
    html {
        font-size: 16px;
        font-family: "Times New Roman";
    }

    /* remove margin and padding from body */
    html > body {
        margin: 0;
        padding: 0;
    }
    html > body > *:nth-child(1),

    /* remove margin and padding from container of header / footer container */
    html > body > *:nth-child(3) {
      margin: 0 !important;
      padding: 0 !important;
    }

    /* set width of header / footer container */
    html > body > *:nth-child(1) > *,
    html > body > *:nth-child(3) > * {
      width: 100%;
      position: relative;
    }
  </style>
